### ISSUE TITLE
part 2 feedback

### ISSUE THREAD

**Issue by andreashandel** [tchu3273/ZaneBillings-TzuChunChu-MADA-project#1]
I don't see any EDA results in the manuscript file and there isn't any EDA.Rmd type file. where is all the EDA?

also, i suggest you start moving toward the project structure where main file and supplementary file contain the bulk of results (tables/figures).

and please remove anything that's not part of the project, and/or update files (e.g. readme).

**Comment by wzbillings** [comment]
fixed in commit 536dd9
